[versions]
quarkus = "3.37.0"
muyun-database = "3.26.14"
junit = "6.1.1"
assertj = "3.27.7"
mockito = "5.20.0"
postgresql = "42.7.11"
testcontainers = "1.21.4"
lombok = "1.18.46"
caffeine = "3.2.4"
jackson = "2.22.0"
poi = "5.5.1"

[libraries]
muyun-database-core = { module = "net.ximatai.muyun.database:muyun-database-core", version.ref = "muyun-database" }
muyun-database-quarkus = { module = "net.ximatai.muyun.database:muyun-database-quarkus", version.ref = "muyun-database" }
quarkus-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
quarkus-arc = { module = "io.quarkus:quarkus-arc" }
quarkus-rest-jackson = { module = "io.quarkus:quarkus-rest-jackson" }
quarkus-jdbc-postgresql = { module = "io.quarkus:quarkus-jdbc-postgresql" }
quarkus-narayana-jta = { module = "io.quarkus:quarkus-narayana-jta" }
quarkus-scheduler = { module = "io.quarkus:quarkus-scheduler" }
quarkus-junit5 = { module = "io.quarkus:quarkus-junit5" }
quarkus-junit5-mockito = { module = "io.quarkus:quarkus-junit5-mockito" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poi" }

[plugins]
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
