package net.ximatai.muyun.spring.platform.config;

public enum LowCodePackageConflictType {
    MODULE_ALREADY_HAS_VERSION,
    PAGE_ONLY_REQUIRES_EXISTING_MODULE,
    TEMPLATE_TARGET_MODULE_EXISTS,
    REQUIRED_DEPENDENCY_MISSING,
    OPTIONAL_DEPENDENCY_MISSING,
    DEPENDENCY_RESOLVER_MISSING
}
